### ISSUE TITLE
URIError: Malformed encodeURI input

### ISSUE THREAD

**Issue by bradzickafoose** [iambumblehead/form-urlencoded#41] opened 2022-01-04 21:34 UTC
I'm seeing a "URIError: Malformed encodeURI input" error at `encodeURIComponent` when emoji are passed in as the `value` to `encode(value)`. 

It looks like the error is coming from [line 7, `.replace(/[^ !'()~*]/gu, encodeURIComponent)`](https://github.com/iambumblehead/form-urlencoded/blob/6beb8f9c9a5a1648e57773d22dd3421165a7f120/form-urlencoded.mjs#L7), when `encode(value)` is called within `nest` on [line 34, `f = encode(name) + '=' + encode(value);`](https://github.com/iambumblehead/form-urlencoded/blob/6beb8f9c9a5a1648e57773d22dd3421165a7f120/form-urlencoded.mjs#L34).

The error doesn't occur on all emoji. 

Here are a few emoji that have triggered the error in React Native on iOS and Android:  😎, 😅, 😍, 👀

**Comment by iambumblehead** [comment] 2022-01-04 21:44
@bradzickafoose would you check and see if your toolchain is preserving the 'u' in the '/gu' part of the regular expression?

this runs for me
```javascript
['😎', '😅', '😍', '👀'].map(value => String(value)
    .replace(/[^ !'()~*]/gu, encodeURIComponent)
    .replace(/ /g, '+')
    .replace(/[!'()~*]/g, ch =>
      `%${ch.charCodeAt().toString(16).slice(-2).toUpperCase()}`))
```

**Comment by iambumblehead** [comment] 2022-01-04 21:51
@bradzickafoose if you are using babel, and if babel is removing the unicode 'u' from the regular expression, you might try using this plugin https://babeljs.io/docs/en/babel-plugin-proposal-unicode-property-regex

**Comment by iambumblehead** [comment] 2022-01-06 05:32
I'm closing this because I can't reproduce it and there is no reply here. Feel free to re-open or send a message me if you feel there is an issue.

**Closed by iambumblehead** 2022-01-06 05:32 UTC

**Comment by bradzickafoose** [comment] 2022-01-10 17:35
Thank you for your help. 

The only way I could get it to not throw a URIError was to replace the `encode` logic with something like, `const encode = (value) => encodeURIComponent(value);` 

I tried the solution you suggested but that didn't work, in this case.

**Comment by iambumblehead** [comment] 2022-01-10 18:04
@bradzickafoose I'm interested to update this package if there is an issue with iOS and Android environments.

Would you try this 'encode' variant which does not use the unicode regex flag? do react native generated sources using this regexp run correctly in iOS and Android?
```javascript
  var encode = function encode(value) {
    return String(value).replace(/(?:[\0-\x1F"-&\+-\}\x7F-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])/g, encodeURIComponent).replace(/ /g, '+').replace(/[!'()~*]/g, function (ch) {
      return "%".concat(ch.charCodeAt().toString(16).slice(-2).toUpperCase());
    });
  };
```

**Comment by iambumblehead** [comment] 2022-01-10 18:10
perhaps this issue is related https://github.com/facebook/react-native/issues/29807
